### ISSUE TITLE
EclipseErrorReporter reports errors in the wrong file

### ISSUE THREAD

**Issue by petervdonovan** [lf-lang/lingua-franca#1030]
I am not sure if this problem is on my end or if it is on the Eclipse side. The path I provide to `EclipseErrorReporter` is `/resource/temp/src/TraceTesting.lf`, but the resource that comes from invoking `FileUtil.getIResource` is `null`.

This causes warnings to be reported on the main file on the wrong lines in cases where they should be reported on the imported file instead. This can be reproduced by opening the Python version of [ModalActions.lf](https://github.com/lf-lang/lingua-franca/blob/python-modal-models/test/Python/src/modal_models/ModalActions.lf) in Epoch.

**Comment by lhstrh** [comment]
This sounds like it has to do with the recent changes to `FileConfig`. @cmnrd: can you have a look?

**Comment by cmnrd** [comment]
I can't reproduce this. When I compile ModalActions.lf. I only get a large error message appearing on top of the file. But there are no warnings reported.

I was investigating this nonetheless. I found that error reporting for C examples for errors in C code in imported reactors is also broken and shows the same symptoms as you describe. However, this appears to be caused by erroneous paths passed to the error reporter. For some reason, the provided path is missing the initial `/`. So the path given to the error reporter is `some/path` instead of `/some/path`. I suspect the error parsing done in the C generator, but I was not able to find the root cause.

I am not sure where exactly and how you are trying to report an error. However, any path given to the error reporter is expected to be a filesystem path. It looks like what you provide is a resource. You can convert a resource to an FS path with `FileUtile.toPath`.
