### ISSUE TITLE
Diagram-guided code navigation is broken

### ISSUE THREAD

**Issue by lhstrh** [lf-lang/lingua-franca#1034]
Clicking on reactions or reactors no longer take you to the corresponding code block. The issue is confirmed in Epoch on `master`. I'm not sure about the VS Code extension.

**Comment by petervdonovan** [comment]
I cannot reproduce this in either VS Code or Epoch after pulling `master` just now and rebuilding both. When I click on a reaction while in Epoch, it is highlighted like this:
![Screenshot from 2022-03-11 19-59-34](https://user-images.githubusercontent.com/33707478/158002876-5ce35b2b-9efb-4fb4-b8af-ab9284bd8bbb.png)

Sometimes it seems like this feature doesn't work because you are clicking on an imported reactor. It also looks like there is an option to disable it. Maybe one of these possibilities is the culprit?

**Comment by edwardalee** [comment]
I find that this highlighting features fails intermittently. After using Epoch for a while, it stops working.  I have not identified what actions cause this.  Sometimes, restarting Epoch restores the highlighting.

**Comment by lhstrh** [comment]
This being difficult to reproduce, I think we should move this to the next milestone. That said, shouldn't we enable navigation to imported files as well? What would it take to enable this?

**Comment by a-sr** [comment]
> ... That said, shouldn't we enable navigation to imported files as well? What would it take to enable this?

It was a bit more complicated than initially anticipated but PR #1055 adds support for this now.
