### ISSUE TITLE
Python target does not work with Epoch

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/lingua-franca#1163]
To reproduce:
```
cd lingua-franca/test/Python
rm -rf src-gen bin
```
Then compile any LF program, e.g., `src/ActionDelay.lf`.  Try to run it:
```
python3 src-gen/ActionDelay/ActionDelay.py
Traceback (most recent call last):
  File "/Users/eal/lingua-franca-master/git/lingua-franca/test/Python/src-gen/ActionDelay/ActionDelay.py", line 6, in <module>
    from LinguaFrancaActionDelay import (  # pylint: disable=no-name-in-module, import-error
ModuleNotFoundError: No module named 'LinguaFrancaActionDelay'
```

`lfc` works, however.

**Comment by Soroosh129** [comment]
For me, on an M1 MacBook Air, this happens because the Epoch IDE is running in x86 emulated mode and thus compiles ActionDelay.lf using the x86 architecture. I can't subsequently run the generated code in a terminal due to the mismatch between the native arm64 that the terminal uses and the x86 architecture of the generated Python module:

```bash
python3 /Users/soroush/lingua-franca-master/git/lingua-franca/test/Python/src-gen/ActionDelay/ActionDelay.py

Traceback (most recent call last):
  File "/Users/soroush/lingua-franca-master/git/lingua-franca/test/Python/src-gen/ActionDelay/ActionDelay.py", line 6, in <module>
    from LinguaFrancaActionDelay import (  # pylint: disable=no-name-in-module, import-error
ImportError: dlopen(/Users/soroush/Library/Python/3.9/lib/python/site-packages/LinguaFrancaActionDelay.cpython-39-darwin.so, 0x0002): tried: '/Users/soroush/Library/Python/3.9/lib/python/site-packages/LinguaFrancaActionDelay.cpython-39-darwin.so' (mach-o file, 
->**but is an incompatible architecture (have 'x86_64', need 'arm64e'))**<-
```

**Comment by lhstrh** [comment]
You are both on Macs. Is this a Mac issue?

**Comment by Soroosh129** [comment]
> You are both on Macs. Is this a Mac issue?

I'm sure mine is, but @edwardalee's issue I believe could be due to multiple Python installations.

**Comment by a-sr** [comment]
I have the same issue as Edward on Ubunutu

**Comment by Soroosh129** [comment]
This could potentially happen if you have multiple version of Python installed and there is a mismatch between what Epoch uses to build the program and what the terminal uses to execute the program.

The module that is built by Epoch (which is in the src-gen folder) will have a specific Python version in its name and will only work with that Python version.

**Comment by a-sr** [comment]
I have Python 2.7 and 3.8 in parallel but I could not find any indications for multiple versions of Python 3.

However, I noticed that in my case there is also an error during compilation:
```
--- Executing command: pylint --output-format=json BanksCount3ModesSimple.py
INFO: /resource/LF%20Tests/Python/src/modal_models/BanksCount3ModesSimple.lf line 28
Exactly one space required around comparison
if __name__=="__main__":
           ^^ [BanksCount3ModesSimple.py:209:12]
ERROR: /resource/LF%20Tests/Python/src/modal_models/Count3Modes.lf line 1
Unable to import 'LinguaFrancaBanksCount3ModesSimple' [BanksCount3ModesSimple.py:13:1]
...
```
I had a look at the code and it seems the compiler does not invoke python to install the module if the linter fails, but the linter fails because the module is missing.

**Comment by Soroosh129** [comment]
Interesting. I thought this particular issue was resolved. Perhaps @petervdonovan would know more about this issue.
