### ISSUE TITLE
Port labels overlap with connections

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/lingua-franca#1273]
The [Big](https://github.com/lf-lang/benchmarks-lingua-franca/blob/main/C/Savina/src/micro/Big.lf) benchmark displays as follows:

<img width="972" alt="image" src="https://user-images.githubusercontent.com/8513334/177208612-9be56dce-575f-4a3c-bc43-055b22298640.png">

Note the overlapping labels.

**Comment by a-sr** [comment]
@soerendomroes If the `PortLabelPlacement.NEXT_TO_PORT_IF_POSSIBLE` option is active, it produces this result for labels on ports that form a direct self loop. It looks like the layout either treats the ports as unconnected or connected through the node.

As a workaround, PR #1274 deactivates the option until the bug is fixed in ELK.

**Comment by lhstrh** [comment]
Closed via #1274.
