### ISSUE TITLE
Eclipse build fails in master

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/lingua-franca#1436]
Eclipse build fails in master because CliBase.java, LFStandaloneModule.java, Lfc.java, and other classes reference ReportingUtil.kt.  Does that class have to be Kotlin?

There is also this error:

Description	Resource	Path	Location	Type
Bundle 'org.lflang.epoch.external.dependencies' cannot be resolved	MANIFEST.MF	/org.lflang/META-INF	line 19	Plug-in Problem

**Comment by cmnrd** [comment]
This class does not have to be Kotlin (non of our classes have to). But I would consider converting it back to Java a step backwards.

This issue was caused by merging https://github.com/lf-lang/lingua-franca/pull/1422. This PR integrates the contents of `org.lflang.cli` into `org.lflang` as a first step for simplifying our source tree layout (see https://github.com/lf-lang/lingua-franca/issues/1276). I think the problem occurs now, because Eclipse simply did not compile `org.lflang.cli` before since it is not needed for Epoch.

Since the `cli` subpackage is not used by Epoch, my proposal is to exclude it from the source list. Should this not work for some reason, I would propose to convert all classes in `cli` to Kotlin, as then they are effectively ignored by Eclipse.
