### ISSUE TITLE
Replace Apache commons CLI

### ISSUE THREAD

**Issue by oowekyala** [lf-lang/lingua-franca#1468]
Apache Commons CLI is unfortunately not a very good CLI parser. It implements just the bare minimum, eg there is no support for argument validation. The programmatic API is also pretty cumbersome to use.

I would consider replacing it with [picocli](https://picocli.info/), which is a very feature-rich CLI parser. The help text it generates looks very nice, and it can even generate completion scripts for Bash and Zsh. It's also very easy to use as you just define you options with annotations on fields, which are then injected by the CLI parser.

**Comment by cmnrd** [comment]
Sounds good! I was also surprised by how many features that I an used to by now are missing from the Apache parser, but I didn't start looking out for alternatives so far.

**Comment by lhstrh** [comment]
Also tagging @patilatharva who started looking into argument validation.

**Comment by patilatharva** [comment]
I looked into Picocli, and I'm also in favor of migrating to it. Instead of entrenching ourselves deeper into Apache Commons CLI by adding custom features (e.g. validation) to it, I think it would just be more readable and maintainable to use a modern CLI tool like Picocli.

Some features of Picocli that seem useful:
- Easy command line parsing, options can be declared through annotations or programmatically.
- Strongly typed everything - command line options as well as positional parameters.
- Built-in + custom validation
- full support for both GNU style and POSIX clustered short options (so it handles `<command> -xvfInputFile` as well as `<command> -x -v -f InputFile`).
- An arity model that allows a minimum, maximum and variable number of parameters, e.g, `"1..*"`, `"3..5"`.
- Support for subcommands
- Extensive documentation

Here's an article that talks about migrating from Commons CLI to Picocli: https://picocli.info/migrating-from-commons-cli.html.
Would it be okay if I get a PR started for this?

**Comment by lhstrh** [comment]
Sounds good to me!
