### ISSUE TITLE
Target tracing property is not "inherited" is all the generated individual federates

### ISSUE THREAD

**Issue by ChadliaJerad** [lf-lang/lingua-franca#1597]
To reproduce, consider [DistributedCount.lf](https://github.com/lf-lang/lingua-franca/blob/master/test/C/src/federated/DistributedCount.lf), where `Count` reactor is declared in the file and `Print` reactor is imported. 

When `tracing` is set to `true` in the target properties, only `c.lft` is generated (instance of `Count`).
If, however, both reactors are declared in the `lf` file, then both traces are generated.

The issue is when calling `generateTarget()` in [`FedTargetEmmitter`](https://github.com/lf-lang/lingua-franca/blob/master/org.lflang/src/org/lflang/federated/generator/FedTargetEmitter.java). The main file target properties are kind of lost when merging with the properties of the imported reactor.

**Comment by ChadliaJerad** [comment]
I forgot to mention that one needs to be under `tracing-federates` branches, in both `Lingua-Franca` and `reactor-c`, to get the `lft` files of `federates`.

If on master, however, it is possible to simply compile the `lf` program, and then check the individual `lf` files under `fed-gen/src`, to see that the imported reactor does not have `tracing: true` in its `target`.

**Comment by lhstrh** [comment]
See https://github.com/lf-lang/lingua-franca/issues/1560 which poses the question as to whether imported reactors should inherit target properties from the file that imports them. To me, it's not clear that they always should. Currently, most target properties are not inherited or merged. The right answer is probably to have this kind of configuration at the level of a project, not at the level of a file, but that is future work. I have pushed a change (bae32dff403b570c5297cdef7e26ed29b302b059) to `tracing-federates` that alters the behavior from "ignore-by-default" to "reset-by-default". We can go with that if it is a better fit and breaks no tests... In the meantime, let's close this issue since it's duplicate.
