### ISSUE TITLE
Replace use of unofficial KlighD Maven repo with official one, soon as it exists

### ISSUE THREAD

**Issue by lhstrh** [lf-lang/lingua-franca#1615]
- [ ] `org.lflang.tests/build.gradle`
- [ ] `org.lflang/build.gradle`

**Comment by cmnrd** [comment]
This is also related to #802 and #897. According to [this comment](https://github.com/lf-lang/lingua-franca/pull/1713#issuecomment-1531144692), we can expect a Maven release with in the next weeks. Since it is unlikely that we can do the switch for the 0.5.0 milestone, I moved this and related issues to 0.6.0.
