### ISSUE TITLE
After delays on split connections are rendered multiple times instead of only once

### ISSUE THREAD

**Issue by cmnrd** [lf-lang/lingua-franca#1625]
This minimal program connects a bank of source reactors to two sink reactors using an after delay connection.
```
target Cpp

reactor Src {
    output out: int
}

reactor Sink {
    input in: int
}

main reactor {
    src = new[2] Src()
    sink1 = new Sink()
    sink2 = new Sink()

    src.out -> sink1.in, sink2.in after 20 msec
}
```
The resulting diagram looks like this:
![Screenshot_20230306_162034](https://user-images.githubusercontent.com/6460123/223153974-e9729b30-6541-478e-b417-98386dc6d58a.png)

Notice how the after delay is duplicated. While the rendering is technically correct, it would be much simpler to only show the after delay once and then split up the connection. This is also what happens in the implementation of after delays (both in the AST transformation and the runtime implementations).

**Comment by soerendomroes** [comment]
This problem cannot be solved using the underlying layout algorithm in ELK and the KLighD synthesis. The synthesis does not know whether both labels will be only be one label. The layout algorithm always places both labels and provides no options to merge labels since it considers labels to just be boxes that need to be placed somewhere.

A general approach to find the correct number of labels to minimize the width and the number of labels necessary seems hard and will most likely never be added to ELK since it has only limited uses and no one is currently researching label placement strategies.
