### ISSUE TITLE
Valid time value rejected as invalid

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/lingua-franca#1651]
The following valid LF program fails to compile:
```
target C

reactor C(
    period: time(5 ms)
) {
    timer t(0, period)
}

reactor A(
    period: time(5 ms)
) {    
    a = new C(period = period)
}

reactor B extends A {}

main reactor {
    a = new B()
}
```
Attempting to compile it gives the following error:
```
ealmac:C eal$ lfc src/rosace/ParameterBug.lf 
lfc: error: Invalid time.
--> src/rosace/ParameterBug.lf:6:16
  |
5 | ) {
6 |     timer t(0, period)
  |                ^^^^^^ Invalid time.
  |
7 | }

lfc: fatal error: Aborting due to 1 previous error.
```

**Comment by edwardalee** [comment]
I assigned this to you because you changed how the validity of a time was checked. See commit #7c530cd.  I think if we revert that commit, the problem will likely go away.

**Comment by cmnrd** [comment]
This commit is a year old and I don't see any connection to the problem her. On the contrary, searching the code base for "Invalid time." let me to [TimerInstance](https://github.com/lf-lang/lingua-franca/blob/4c4b4119b41590876abad97f4a0bb0d9cb1751d9/org.lflang/src/org/lflang/generator/TimerInstance.java#L73) which produces the error message. It appears that this happens because [ASTUtils.initialValue](https://github.com/lf-lang/lingua-franca/blob/4c4b4119b41590876abad97f4a0bb0d9cb1751d9/org.lflang/src/org/lflang/ASTUtils.java#L1219) throws an `IllegalArgumentException`. Judging from the code, it seems to check if the parameter reference belongs to the correct reactor instance, which apparently it does not when inheritance is involved. Perhaps this check can be simply removed, but I don't understand this part of the code base well enough to judge.

**Comment by cmnrd** [comment]
It looks like https://github.com/lf-lang/lingua-franca/pull/1580 might solve the problem.
