### ISSUE TITLE
Name collisions between files generated for federated programs

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/lingua-franca#1702]
Another recently introduced error that I think may be a consequence of the bodiless reactions merge:
 
The following minimal program:
```
target C
reactor A {
    reaction(startup){=
        printf("Hello\n");
    =}
}
federated reactor {
    a = new A()
}
```
Generates the following warning when compiled with lfc:
```
/Users/eal/lingua-franca-intellij/test/C/fed-gen/Bug/src-gen/a/a1452928096_main.c:3:10: warning: non-portable path to file '"include/a/A.h"'; specified path differs in case from file name on disk [-Wnonportable-include-path]
#include "include/a/a.h"
         ^~~~~~~~~~~~~~~
         "include/a/A.h"
1 warning generated.
```
There are apparently now **two** header files generated for each reactor, one for the class `A.h` and one for the instance `a.h`. Why is a header file being generated for the instance?  On MacOS, these are the same file.

There used to be only one header file generated.  Moreover, there are now a slew of other new files that have appeared with names like `a1704353662.c`.  Where are these numbers from? What are these files?  Do we really need all these files?  How did they appear?

**Comment by petervdonovan** [comment]
> There used to be only one header file generated. Moreover, there are now a slew of other new files that have appeared with names like a1704353662.c. Where are these numbers from? What are these files? Do we really need all these files? How did they appear?

First I would like to make sure that anyone experiencing this issue is aware of the explanation at the top of #1599. It is the intended behavior resulting from that PR.

I was under the impression that people generally agreed that it would be a good idea to separate the generated code out into multiple files. This has some small benefits. For example,
* It allows static variables declared in preambles to have file-level scope.
* It may make it slightly easier for us to reduce naming collisions.
* It may make it easier to find things in the generated code.
* In the future, it may also result in shorter compilation times due to incremental building, although I have not verified that and am not sure.

We don't have to keep things in multiple files, and if we want to revert that part of #1599, we can. But I have a personal preference to put code for different reactor classes in different files.

> On MacOS, these are the same file.

If we do not revert #1599, then we should fix this! I am surprised that we have this issue and it might be good to check that it still exists after deleting `src-gen` and rebuilding.

**Comment by edwardalee** [comment]
I see some really big red flags:

* It seems that .c and .h files are being generated not only for reactor class definitions, but also for instances.  This will result in a huge number of files for many applications. In my example, "A" is a reactor class and "a" is a reactor instance.  We get "a.h" and "A.h" files.
* We need to assess the impact on code size.  We are already having trouble getting code into some embedded platforms.

**Comment by petervdonovan** [comment]
I think that these two red flags are actually the same thing: We do not want to generate asymptotically more code than we need to. I agree that generating code for every instance would be a terrible idea; fortunately, I do not think that I did that. Perhaps what you are referring to is the difference between "mangled" and "user-visible" header files, which I explained at the top of #1599.

I would also like to point out that having a constant factor more header files than we think is strictly necessary should not result in any increase in code size. I am under the impression that typedefs and declarations (as opposed to definitions) do not increase code size.

**Comment by petervdonovan** [comment]
Update: OK, I see now why it looks like code is being generated for reactor instances. This is specific to federated programs. In a federated program, the federated reactor, which is an instance, is given its own special class corresponding to the main reactor. For example, the main reactor of `a.lf` in `fed-gen` results in the creation of a class called `a`.

So, we aren't creating a new header file for each instance; instead, it is still true that we are just creating a new header file for each class. However, in this case it results in a naming collision because something else is already called `A`. This is bad, and it's my mistake -- we should fix it. But it isn't the same as the problem that you describe.

**Comment by edwardalee** [comment]
Ah, yes, this makes sense. I guess this easy enough to work around for now, but it is still a bug.
