### ISSUE TITLE
Declaration in preamble results in duplicate symbols

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/lingua-franca#1705]
We can no longer define things in the preamble.
Minimal example:
```
target C
preamble {=
    const char hello[] = "Hello";
=}
main reactor {
    reaction(startup) {=
        lf_print("%s", hello);
    =}
}
```
This gives the following compile error:
```
[100%] Linking C executable Bug
duplicate symbol '_hello' in:
    CMakeFiles/Bug.dir/bug704869156_main.c.o
    CMakeFiles/Bug.dir/Bug.c.o
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by petervdonovan** [comment]
[I thought that you were OK with this based on our discussion here.](https://github.com/lf-lang/lingua-franca/pull/1599#issuecomment-1445013124) This change is listed in the change summary of #1599.

@cmnrd said that [we could solve this using `public` and `private` preambles](https://github.com/lf-lang/lingua-franca/pull/1599#issuecomment-1458592657) -- if the current behavior isn't acceptable to us, then maybe we should do what he said.

**Comment by edwardalee** [comment]
What exactly is a file-level preamble useful for then?  If its definitions are not visible in the file, what can it be used for? How do we explain to users what the can and cannot use it for?

As a general rule, I believe that writing documentation should be an integral part of any design process.  If the documentation is hard to write, then there are probably flaws in the design.  Can you propose how the handbook explanation of preambles needs to change?

**Comment by lhstrh** [comment]
https://www.lf-lang.org/docs/handbook/preambles?target=cpp#preamble

**Comment by petervdonovan** [comment]
The idea behind my change was simple: Declarations should go in file-level preambles, and declarations should go in reactor-level preambles. By following this principle I got all of our tests and benchmarks to run correctly, and I think that the process of converting to this approach is straightforward and easy to explain. However, Christian has an idea about how to solve this using public and private preambles, and I think his opinion is reasonable. I don't have a strong opinion about how we resolve this issue, and as soon as it is settled in a way that is documentable, then I agree that the semantics of preambles for the C target should be documented.

The fact is that before my change, everything was all in the same file, and in order to make sense of the preambles you had to reason about how the generated code would be arranged in order to figure out what was and was not in scope. Furthermore, the `static` keyword did not prevent all reactors from having access to the same variable.

**Comment by edwardalee** [comment]
OK, but I still don't understand. You say, "Declarations should go in file-level preambles, and declarations should go in reactor-level preambles."  Should one of these "declarations" be "definitions"?  If so, I don't understand how this works. Either what is in the file preamble is in scope or it is not, regardless of whether it contains declarations or definitions, and it appears from my example that it is not in scope. In that case, what *can* it be used for?

**Comment by petervdonovan** [comment]
Sorry, the second one was supposed to be "definitions." The difference between declarations and definitions is that declarations can appear in multiple different compilation units. Concretely, this means multiple `.c` files can include some of the same declarations. This is necessary in order for multiple files to call into the same libraries; they all need to know that the functions that they are calling exist. Definitions cannot appear in multiple compilation units because if they did, then that would create ambiguity about which definition to use. As I understand, that is what the linker is saying here: there are multiple definitions of the global constant `hello`, so it does not know which one to use.

**Comment by petervdonovan** [comment]
Another way of explaining what I did is to say that file-level preambles are `public` preambles and reactor-level preambles are `private` preambles.

**Comment by edwardalee** [comment]
OK, this is starting to get clear enough to be able to document, though it's still a bit fuzzy to me. Is a "public" preamble (outside any reactor definition) visible only within the same .lf file? Or can it somehow be \#include'd in other .lf files. If so, how?

I guess also we need to guide the users about how to interpret compiler error messages that they get.  I guess here that the "duplicate symbols" problem is because the generated .h file is \#include'd in more than one place?  Another option would be to surround the generated .h file \#ifdef, as is usually done with .h files.  This would result in more permissive code, where our policy is not enforced.  But I'm not sure we want to do that, if we can provide adequate guidance to the user about how to prevent these errors.  One rather nice thing about your design is that it makes harder for programmers to "cheat" with global variables.

**Comment by petervdonovan** [comment]
> I guess here that the "duplicate symbols" problem is because the generated .h file is #include'd in more than one place? Another option would be to surround the generated .h file #ifdef, as is usually done with .h files.

That is being done, I think, but it does not solve the problem. Include guards only prevent multiple inclusion within a given compilation unit, but they do not prevent definitions from appearing in multiple different compilation units.

>  Is a "public" preamble (outside any reactor definition) visible only within the same .lf file? Or can it somehow be #include'd in other .lf files. If so, how?

Okay, so this is where it gets complicated. The documentation for the C++ target also comments that "the precise interactions of preambles and imports can become confusing," but the short answer is that the file-level preamble (which I treat as `public`) is not in a file, but instead is copied and pasted into all of the files that require it. Files that require it include files for reactor classes that are defined in the same file, as well as all reactor classes in all files that (either directly or transitively) import reactor classes from the file of the file-level preamble. In retrospect, I realize that we could have just put the top-level preamble in the header files corresponding to reactor classes that are defined in the file of the file-level preamble.

This means that with the current design, it isn't possible for the user to `#include` the file-level preamble in places where it isn't already available. But we can change that if we want to.

**Comment by edwardalee** [comment]
I have issued [PR 137](https://github.com/lf-lang/lf-lang.github.io/pull/137) on the website repository that documents the new behavior.  It is certainly more restrictive than the previous design, but once I understood it, I really agree that this is the right way to go. Nice job!

**Comment by nan-af** [comment]
Please update the example code in https://www.lf-lang.org/docs/writing-reactors/multiports-and-banks#initializing-bank-members-from-a-table to reflect these changes.

**Comment by lhstrh** [comment]
> Please update the example code in https://www.lf-lang.org/docs/writing-reactors/multiports-and-banks#initializing-bank-members-from-a-table as it fails to compile.

Thanks for pointing out the issue. Could I invite you to submit a PR to the website repo with a fix?
