### ISSUE TITLE
Print warnings in `lfc` even if there are errors

### ISSUE THREAD

**Issue by lhstrh** [lf-lang/lingua-franca#1859]
The message printed when there exists ambiguity in the program (see #1853) could arguably be an warning instead of an error, but it turns out warnings are not shown by `lfc`. We should fix this.

**Comment by cmnrd** [comment]
Do you have an example where warnings are not reported by lfc? It works fine for me on master. For instance
```
target Cpp {
  keepalive: true
}

main reactor Minimal {
  reaction(startup) {= std::cout << "Hello World!\n"; =}
}
```
produces
```
--> test/Cpp/src/Minimal.lf:3:3
  |
2 | target Cpp {
3 |   keepalive: true
  |   ^^^^^^^^^ The keepalive property is inferred automatically by the C++ runtime and the value given here is ignored
  |
4 | }
```

**Comment by lhstrh** [comment]
When I turned the `error` in #1853 into `warning`, it didn't show up...

**Comment by cmnrd** [comment]
I just tried this out and indeed the warning wasn't shown for me either on first try. This is because you will get a linker error if you make a reaction bodyless for testing, but don't provide the implementation. The issue reporter in lfc collects all issues during the run, but it does not print the issues immediately (so that they are not intermingled with the cmake output). In this case, the issue reporter will collect two issues: the warning message and the linker error. Currently, lfc does not print warnings if there are errors. Hence, the warning is not printed, only the linker error. If you run lfc with `--no-compile` it will print the warning message as no compilation error occurs.

So, the question for this issue is: do we want to keep the current behavior or should we always print warnings.

**Comment by lhstrh** [comment]
> So, the question for this issue is: do we want to keep the current behavior or should we always print warnings.

I think that (in hindsight), we should always print warnings.
