### ISSUE TITLE
Definitions in a private preamble are not in scope for the state variables 

### ISSUE THREAD

**Issue by erlingrj** [lf-lang/lingua-franca#1954]
I have found that in the Cpp target I cannot use definitions from a private preamble for my state variables. It makes sense that the port definitions need to be in a public preamble (visible outside the reactor), but the state variables could use definitions from a private preamble.

**Comment by cmnrd** [comment]
Are you doing smth like this:
```
private preamble {=
    using foo = int;
=}
state bar: foo = 0;
```
?

If so, then this is expected to fail. C++ classes are defined by their members, including all state variables. Consequently, all types of state variables need to be visible when declaring the class. This is only the case when the types are defined in a header (i.e., the public preamble).

Think of the public preamble as everything that needs to be known in order to declare the reactor class (i.e. the public interface), and of the private preamble as everything that needs to be known to define the behavior (i.e., the implementation of all reactions and methods). Note that here public and private are not related to the meaning of the public and private keyword in C++. They are more related to the concept of private and public dependencies as used in cmake. I know this is a bit confusing, but so far I haven't found better names.

**Comment by cmnrd** [comment]
> This means that any other reaction within the same LF file, or in any other LF file which includes this one. (But not necessarily in ALL LF files of the program?) They will all have foo defined? 

>  If this is the case, it is a little unfortunate. Especially if you are including external libraries which should only be used within a particular reactor, if you now use any definition from the library in your state variable, it now must be included for the other reactors as well.

This is just how C/C++ works. If you write a class and add a private member variable of a type defined in an external header, you need to include that header. And anyone who includes your class header, automatically also includes the library header. The dependency on the library is public, as any user of the class will need to also have the library headers available.

**Comment by cmnrd** [comment]
I don't know what your use case is, but if you really need to avoid this "dependency leakage", you can define yourself an abstract class that wraps the access to your library data type. Then your state variable should be a unique pointer to the abstract class. In the private preamble you can then define a concrete implementation, and instantiate it in a startup reaction.
