### ISSUE TITLE
Basic array initialization doesn't work in Cpp

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/lingua-franca#1980]
I'm trying to update [Expressions.md](https://www.lf-lang.org/docs/handbook/expressions?target=cpp), and unfortunately, basic array initialization of state variables doesn't seem to work with the Cpp target.  Consider this program:

```
target Cpp

reactor Foo {
  state x: int[](1, 2)

  reaction(startup) {= std::cout << x[0] << " " << x[1] << std::endl; =}
}

main reactor {
  f = new Foo()
}
```

Compiling and running this gives the wrong answers:

```
2 0
```

**Comment by cmnrd** [comment]
This is the expected behavior for the provided syntax. Across targets, we interpret the `type[]` syntax as a variable sized list and `type[N]` as a fixed-size list. Plain arrays shouldn't been used in C++. Therefore, `type[]` is translated to an `std::vector` and `type[N]` to an `std::array<N>`. However, this is rather an implementation detail.

`state x: int[](1, 2)` is interpreted as a constructor call to `std::vector` and this is defined such that the first argument is a count of elements and the second is the element to fill the vector with. So your code constructs a vector with 1 element of value 2 in it.

To initialize an array or vector with concrete values in C++, one should always use an initializer list. The following lines should all yield the expected result:
```
state x: int[] = {1, 2}
state x: int[]({1, 2})
state x: int[2] = {1, 2}
state x: int[2]({1, 2})
```

Note that this is exactly the behavior described in the docs under [Collections](https://www.lf-lang.org/docs/handbook/expressions?target=cpp#collections) and in more detail in the [Target Language Details](https://www.lf-lang.org/docs/handbook/target-language-details?target=cpp).

**Comment by edwardalee** [comment]
OK, thanks for the explanation.  I will update the docs accordingly.

Note that this syntax appears to be untested:

```
state x: int[] = {1, 2}
```

The [ArrayAsParameter](https://github.com/lf-lang/lingua-franca/blob/master/test/Cpp/src/ArrayAsParameter.lf) test uses:

```
sequence: std::vector<int> = {0, 1, 2}
```

The [NativeListsAndTimes](https://github.com/lf-lang/lingua-franca/blob/master/test/Cpp/src/NativeListsAndTimes.lf) test uses:

```
p: int[]{1, 2, 3, 4}
```

This latter syntax appears to not be documented anywhere.
