### ISSUE TITLE
What is the diagram option "Reaction level" supposed to do?

### ISSUE THREAD

**Issue by cmnrd** [lf-lang/lingua-franca#2017]
I stumbled across the diagram option "Reaction level" today. However, it does not seem to do anything. I tested this on various programs, but the diagrams did not change when checking or unchecking this option.

**Comment by a-sr** [comment]
@edwardalee added this option, he can probably explain best what it does.
As far as I know, it shows levels that indicate orderings due to dependencies and exposes potential for parallelization of reactions.
What I don't know is how it works. I guess the option will only display something if there was some kind of compilation producing the necessary information.

**Comment by edwardalee** [comment]
I suspect this no longer works because of this change by @petervdonovan in ReactionInstance.java:

```
    // Force calculation of levels if it has not been done.
FIXME
    // FIXME: Comment out this as I think it is redundant.
    //  If it is NOT redundant then deadline propagation is not correct
    // parent.assignLevels();
```

Testing this hypothesis, however, seems rather time consuming now that everything is in separate repos. I don't have time to check this.

**Comment by edwardalee** [comment]
That said, maybe we don't really need this feature? Perhaps easiest to just remove it.

**Comment by cmnrd** [comment]
I was also wondering if it is worth repairing. I'll open a PR removing this synthesis option.
