### ISSUE TITLE
Federated with Deadline fails to invoke reaction

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/lingua-franca#2026]
The following test nondeterministically fails to invoke the first reaction of the `Actuate` reactor.  Removing the deadline in the second reaction of `Actuate` eliminates the problem.  The problem occurs whether the deadline is violated or not.  The mere presence of the deadline statement is sufficient to trigger the bug.

<img width="866" alt="image" src="https://github.com/lf-lang/lingua-franca/assets/8513334/f83a69dd-da89-4ccc-910a-29e60cdab147">

```
target C {
  timeout: 5s
}
preamble {=
  #include "platform.h"
=}
reactor Sense(period:time = 500ms) {
  state count:int = 1
  output out:int
  timer t(0, period)
  reaction(t) -> out {=
    lf_set(out, self->count++);
  =}
}
reactor Process {
  input in:int
  output out:int
  reaction(in) -> out {=
//    lf_sleep(MSEC(35));
    lf_set(out, in->value * 2);
  =}
}
reactor Actuate {
  input in1:int
  input in2:int
  state count:int = 0
  reaction(in1) {=
    printf(PRINTF_TIME ": Received %d\n", lf_time_logical_elapsed(), in1->value);
    self->count++;
  =}
  reaction(in2) {=
    printf(PRINTF_TIME ": Second input: %d\n", lf_time_logical_elapsed(), in2->value);
  =} deadline(30 ms) {=
    printf(PRINTF_TIME ": Second input: %d    ", lf_time_logical_elapsed(), in2->value);
    printf("PANIC! Deadline violated!\n");
  =}
  reaction(shutdown) {=
    if (self->count != 11) {
      lf_print_error_and_exit("Expected the first reaction to be invoked 11 times! Got %d", self->count);
    }
  =}
}
federated reactor {
  s1 = new Sense(period = 500ms)
  s2 = new Sense(period = 1s)
  c1 = new Process()
  a = new Actuate()
  s1.out -> c1.in
  c1.out -> a.in1
  s2.out -> a.in2
}
```

**Comment by edwardalee** [comment]
For this test case and also #2025 the problem appears to be that the GEDF_NP scheduler does not work with federated execution.  This scheduler is selected automatically when a deadline is present.  If I force the scheduler to be NP (the default scheduler), then the test passes.  I suspect the `_lf_sched_insert_reaction` function, which for the NP scheduler has some special code for federated execution and for the GEDF_NP scheduler does not.  But there may be more issues.

**Comment by erlingrj** [comment]
Edward, I have debugged a little and extracted this very strange debug trace. I simplifed the program to this:
![image](https://github.com/lf-lang/lingua-franca/assets/21197938/550339f7-b8dd-4bea-9508-fe0a22c369c4)

Before I dig deeper I want to hear if someone has a clue, @petervdonovan has been making changes to the federated infrastructure also, maybe he at once sees the issue. The following is extracted from a debug trace of the actuator federate. The reaction names are ZERO, ONE, TWO. Also there is NR0_1 and NR1_1 which is the reaction1 at network receiver 0 and network receiver 1. They are receiving the events for each input port. Now the debug trace first shows an example of a timestep where everything works as expected:

```
Federate 1: LOG: --------- Start time step at tag (2500000000, 0).
Federate 1: LOG: Enqueued reaction NR0_1 at time 1696523809880890851.
Federate 1: LOG: Worker 1: Invoking reaction NR0_1 at elapsed tag (2500000000, 0).
Federate 1: DEBUG: There are 1 outputs from reaction NR0_1.
Federate 1: DEBUG: Scheduler: Enqueueing reaction ZERO, which has level 2.
Federate 1: DEBUG: Worker 1: Done with reaction NR0_1.
Federate 1: LOG: Received Time Advance Grant (TAG): (2500000000, 0).
Federate 1: LOG: Worker 1: Invoking reaction ZERO at elapsed tag (2500000000, 0).
2500000000: Received 6
Federate 1: DEBUG: Worker 1: Got from scheduler reaction NR1_1: level: 3, is input reaction: 1, chain ID: 1, and deadline -9223372036854775808.
Federate 1: LOG: Worker 1: Invoking reaction NR1_1 at elapsed tag (2500000000, 0).
Federate 1: DEBUG: There are 1 outputs from reaction NR1_1.
Federate 1: DEBUG: Scheduler: Enqueueing reaction ONE, which has level 4.
Federate 1: DEBUG: Worker 1: Done with reaction NR1_1.
Federate 1: LOG: Worker 1: Invoking reaction ONE at elapsed tag (2500000000, 0).
2500000000: Second input: 6
```

We first enqueue NR0_1 at level 1. Executes it, gets the event and trigger reaction ZERO. Then we execute NR1_1 at level 3 and then reaction ONE. 


However at this timestep it messes up:
```
Federate 1: LOG: --------- Start time step at tag (3000000000, 0).
Federate 1: DEBUG: Triggering reaction NR1_1.
Federate 1: DEBUG: Scheduler: Enqueueing reaction NR1_1, which has level 3.
Federate 1: DEBUG: Scheduler: Enqueueing reaction NR0_1, which has level 1.
Federate 1: LOG: Enqueued reaction NR0_1 at time 1696523810380890851.
Federate 1: LOG: Worker 1: Invoking reaction NR1_1 at elapsed tag (3000000000, 0).
Federate 1: DEBUG: There are 1 outputs from reaction NR1_1.
Federate 1: LOG: Received Time Advance Grant (TAG): (3000000000, 0).
Federate 1: DEBUG: Scheduler: Enqueueing reaction ONE, which has level 4.
Federate 1: LOG: Worker 1: Invoking reaction ONE at elapsed tag (3000000000, 0).
3000000000: Second input: 7
```

Here, we enqueue NR1_1 at level 3 first. And then we start executing it. Then later we enqueue NR0_1 at level 1. This reaction is now forgotten because we just keep incrementing the levels. Actually this reaction is not invoked until the next timestep when we start back at level0.


So how is this possible?

**Comment by erlingrj** [comment]
This might be related to the MLAA. When looking at the debug output with the NP scheduler. We also trigger NR1_1 first, but we block at level0 until NR0_1 is enqueued. With the GEDF scheduler we are allowed to advance to level 3 straight away

**Comment by edwardalee** [comment]
I think this may be a race condition in GEDF_NP. This is similar to what I was seeing, which led me to the conclusion that GEDF_NP is not working. Reactions put on the reaction queues are sometimes executed at a later time and sometimes not executed at all.

**Comment by erlingrj** [comment]
I believe I have found the issue and solved it in [this](https://github.com/lf-lang/reactor-c/pull/282/commits/5f4e96af1c79085bb0f6919c924a1009b3324992) commit. I am a bit hesitant thought because if this is the bug I really cannot understand how it could pass the comprehensive integration tests....

**Comment by petervdonovan** [comment]
> if this is the bug I really cannot understand how it could pass the comprehensive integration tests....

Our integration tests are not comprehensive and cannot reliably detect concurrency bugs. We may feel as though our testing is very thorough and heavyweight because the tests run for hours and are so expensive that we cannot keep adding more of them, but in fact we only have 60ish federated tests, and they are not constructed in a way that makes it possible for them to reliably detect concurrency bugs.

> I believe I have found the issue and solved it in [this](https://github.com/lf-lang/reactor-c/pull/282/commits/5f4e96af1c79085bb0f6919c924a1009b3324992) commit.

Yes, I took a look at your commit and it looks right to me. This issue is almost certainly my bad, so I am glad it's being fixed. Thanks Erling!

**Comment by erlingrj** [comment]
I think it would make sense with some scheduler-specific integration tests. E.g. test that the EDF scheduler actually does EDF in various scenarios. I am pretty sure it has another bug which is that it does the chain optimization even if there are other higher-priority reactions blocked at the next level. Also, we should probably have a physical dedicated and real-time optimized  server for benchmarking the runtime and the different schedulers as part of the CI also...
