### ISSUE TITLE
DistributedPhysicalActionUpstreamLong.lf times out in mac CI

### ISSUE THREAD

**Issue by erlingrj** [lf-lang/lingua-franca#2254]
We are having problems with `DistributedPhysicalActionUpstreamLong.lf` timing out in CI, e.g. [here](https://github.com/lf-lang/reactor-c/actions/runs/8546664692/job/23432390248?pr=400). I have also seen it in another unrelated PR, so it is not about the changes introduced there.

I am not sure what could have introduced this. A hint might be that @petervdonovan merged in #2249 , however it should not affect this because that was Docker-specific.

**Comment by petervdonovan** [comment]
Unless the way timeouts work in our test framework has changed, the CI run that you linked looks like a user cancellation, not a timeout.

**Comment by lhstrh** [comment]
Timeout is set to 120 mins

**Comment by erlingrj** [comment]
I reran with logging enabled, and now it seems to have timed out on a different test: https://github.com/lf-lang/reactor-c/actions/runs/8546664692/job/23459617885?pr=400

**Comment by lhstrh** [comment]
There is a history of the compiler getting stuck on macOS. We don't know why this happens and it doesn't seem to be reproducible. It was assumed that the culprit was here:

https://github.com/lf-lang/lingua-franca/blob/205ed2280a6713636862dae715a145d59f061ef1/core/src/main/java/org/lflang/federated/generator/FedGenerator.java#L339

But in hindsight, I don't think we ever actually solved the problem...
