### ISSUE TITLE
NP scheduler should not change the levels of reactions based on deadlines

### ISSUE THREAD

**Issue by erlingrj** [lf-lang/lingua-franca#2433]
Currently the NP scheduler will modify the levels of reactions based on deadline and inherited deadline thus changing the execution order.

**Comment by edwardalee** [comment]
Actually, it is the GEDF scheduler that does this.  PR #2442 addresses this by removing the feature that automatically selects the GEDF scheduler when deadlines are present.  Now, you have to explicitly select GEDF to get that scheduler.  But the GEDF scheduler will rarely be the best choice on a multicore machine because it sacrifices parallelism.

A better approach would be to use the NP scheduler with [layered scheduling](https://ieeexplore.ieee.org/document/10697337).  An alternative that might simplify layered scheduling, I think, would be to adjust the NP scheduler so that it assigns reactions with earlier deadlines to lower numbered worker threads, and then statically give lower-numbered worker threads higher priority.
