### ISSUE TITLE
Diagrams are not filled in for imported and extended reactors.

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/lingua-franca#341]
In the patterns branch, the programs example/C/src/Patterns/Loop_01_Single.lf and Loop_02_SingleDelay.lf do not get the contents rendered. These import reactors that extend other reactors.

**Comment by lhstrh** [comment]
Wasn't this fixed yet?

**Comment by edwardalee** [comment]
Yes it is fixed.  However, clicking on imported components in the diagram should perhaps open the imported file and highlight the component definition. It does not currently do that.

**Comment by lhstrh** [comment]
@a-sr: is there a reasonably easy fix to implement the behavior that @edwardalee describes? If so, could you push one?

If this is somehow difficult, I propose we close this issue and create a separate one for the click behavior. We can do that as part of a future milestone.

**Comment by a-sr** [comment]
The current behavior is implemented in the klighd framework and it is not really a bug but intended this way.
The basic UX concept is that the editor defines the context for the diagram view. If the selection of a diagram element that is defined in a different resource would jump to the textual source, it would switch to the respective editor and display the diagram for that editor, losing the previous context.
I think this behavior would be annoying because it happens rather often that you select elements without the intent to look at the source code, e.g. to navigate in the model, highlight them for presentation, or expand them.

I could try to add an alternative action, e.g. ctrl+click, to navigate to the source code of reactors in other files. This way, losing context would be intentional but still inconsistent with the default.

@lhstrh I agree, if we want this behavior, we should add a new ticket because this will take some careful consideration in order to provide a pleasant user experience.
