### ISSUE TITLE
In banks of reactors, bank_index is not a proper parameter

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/lingua-franca#343]
Currently, `bank_index` is available for reactors to read inside reactions (see [Banks of Reactors](https://github.com/icyphy/lingua-franca/wiki/Multiports-and-Banks-of-Reactors#banks-of-reactors)). However, it is not a proper parameter of the reactor in the bank. As a consequence, its value cannot be assigned to other reactors and cannot be passed down to contained reactors.  I would like to do something like:
```
    r = new[4] Foo(bar = bank_index);
```
which would assign the bank index to the parameter `bar` of reactor `Foo`.

**Comment by cmnrd** [comment]
It appears that the C target diverged a bit from the original C++ implementation. In C++, `bank_index` is treated as a special parameter. For instance:
```
reactor Foo(bank_index:size_t(0)) {
}
main reactor {
  foo = new[4] Foo();
}
```
In that program, `Foo` will be instantiated 4 times and receive the corresponding `bank_index`. The instantiation automatically overwrites the bank_index parameter if the instantiation is a bank instantiation and the instantiated reactor as a parameter named `bank_index`. Otherwise, the bank_index will not be set. I guess the same could be done in C.

**Comment by edwardalee** [comment]
Yes, the C target should be changed so that bank_index is a parameter. The current design does not support passing the bank_index to contained reactors, which becomes possible if it is a parameter.

**Comment by cmnrd** [comment]
I think this was implemented for the C target (judging from the C tests), but I am not sure. Can we close this?

**Comment by edwardalee** [comment]
Yes, this is fixed in the C target and also in TS. Both can pass bank_index parameters.
