### ISSUE TITLE
Declutter repo and move into separate Github Organization

### ISSUE THREAD

**Issue by lhstrh** [lf-lang/lingua-franca#347]
- [x] create an `lf-lang` organization and move the `lingua-franca` repo from `icyphy` to `lf-lang` 
- [x] put examples in a separate repo
- [x] put experimental code in a separate repo
- [x] factor out C library
- [x] move benchmarks to separate repo

**Comment by lhstrh** [comment]
Putting the examples in a separate repo seems particularly attractive once we have our VS Code plugin released. We don't want to make those users download the sources of the compiler in order for them to use the examples.

**Comment by cmnrd** [comment]
I think also the benchmarks should really live in a separate repo. Factoring everything out that is not part of the LF compiler and IDE will help in implementing a release flow. With examples, benchmarks, etc in the repo, we would need to include those in the release notes, although they are not part of the release artifacts. Also we don't want to bump version numbers just because we updated an example or a benchmark.
