### ISSUE TITLE
Synthesize diagrams from the standalone compiler

### ISSUE THREAD

**Issue by cmnrd** [lf-lang/lingua-franca#398]
While our Epoch IDE is very nice, many people seem to refrain from using Eclipse. I think that the standalone compiler provides a very viable alternative. Thanks to #365 we even have support for syntax highlighting in vim, which is in a way better than the highlighting in Epoch as it includes full target language support (at least for C/C++ for now). However, the only important feature lacking without Epoch is the diagram synthesis, and I think we should make this available also from the `lfc` compiler.

What do you think? Would this be possible? If so, do you have any pointers on how this could be implemented?

**Comment by a-sr** [comment]
Yes, it is possible.
The Klighd framework can save diagrams as png or svg outside of eclipse. An example is the [Kieler Compiler (kico)](https://rtsys.informatik.uni-kiel.de/~kieler/files/release_sccharts_1.2.0/cli/), which has a variant that is able to save diagrams (kicodia). In the [klighd-vscode](https://github.com/kieler/klighd-vscode) project, there is also a standalone tool that allows interactive diagrams in a browser using the language server.

However, the tricky part is building the tool. For LF you could use the same tool chain as for the language server (on the vscode branch) and register a main class that provides saving images ([example from kicodia](https://git.rtsys.informatik.uni-kiel.de/projects/KIELER/repos/semantics/browse/plugins/de.cau.cs.kieler.kicool.ide/src/de/cau/cs/kieler/kicool/ide/cli/KielerCompilerDiagramCLI.xtend)). However, the problematic part is that Klighd uses SWT for rendering, which relies on platform-dependent native code. This the reason for the different jars of kicodia. Each bundles the specific code for SWT. There are also alternative strategies. The LF language server currently excludes SWT and puts the correct platform-dependent jar on the classpath when the language server is started. Hence, the extension ships with one language server jar and three SWT jars, to achieve platform independence. A colleague once produced a solution where he bundled all platform-dependent jar into the tool and wrote a special class loader to include the correct one at runtime but I am not sure if such an solution will always work.

Building with Gradle is also not possible because Klighd is not yet available as proper maven artifacts, see related [Klighd issue](https://github.com/kieler/KLighD/issues/78). Hence, one has to rely on Maven with p2 and a self-written Python script to create a fat/uber jar.

**Comment by cmnrd** [comment]
Closing this in favor of #897.
