### ISSUE TITLE
Cycle highlighting in the diagram view no longer works

### ISSUE THREAD

**Issue by lhstrh** [lf-lang/lingua-franca#447]
While an error message is displayed, the "Filter cycle" or "Display cycle" features ceased to work (all nodes disappear and only the collapsed top-level reactor is shown).

**Comment by edwardalee** [comment]
I have pushed to branch cycle-visualization-bugfix a partial fix for this. However, Connections are still not highlighted.  The offending code is in CycleVisualization.xtend. Specifically, this code is wrong somewhere:
```
                        // Reactor edges
                        for (cycleEgde : reactorNode.outgoingEdges.filter [
                            affectedElements.contains(sourcePort.sourceElement()) && (
            				(
            					!target.sourceIsReactor() && allAffectedElements.values.contains(target.sourceElement())
            				) || (
            					target.sourceIsReactor() &&
                                allAffectedElements.keySet.contains(
                                    target.getProperty(LinguaFrancaSynthesis.REACTOR_INSTANCE)) &&
                                allAffectedElements.get(target.getProperty(LinguaFrancaSynthesis.REACTOR_INSTANCE)).
                                    contains(targetPort.sourceElement())
            				)
            			)
                        ]) {
                            // FIXME: Still hard-coded semantics
                            if (!(cycleEgde.sourceElement() instanceof Connection) ||
                                (cycleEgde.sourceElement() as Connection).delay === null) {
                                cycleEgde.setProperty(DEPENDENCY_CYCLE, true)
                                highlighter.accept(cycleEgde)
                            }
                        }
```
Unfortunately, with the way this code is written, it seems to not be possible to set breakpoints see why the filter is erroneously filtering out Connection objects.  I could rewrite this code in straightforward Java and then debug it, but that would significantly change the coding style. So perhaps it's better for Alex to fix this?

**Comment by a-sr** [comment]
Yes, I will take care of that.

**Comment by a-sr** [comment]
I fixed the remaining problems and opened a PR (#455). In my tests, all cycles are again completely highlighted and the buttons are working. It seems I forgot to adjust the cycle visualization to the new reaction graph.
The code should be more debug-friendly now as well.

I also had a look at the FixMe (see above) that I added when initially writing the highlighting. The problem was (and still is) that a reported cycle only consists of reaction and port instances. Hence, if two ports in a cycle are connected with multiple direct connections but not all of them contribute to the cycle, then I need to filter some out based on semantics.
Here is an example:
![delay_cycle_problem](https://user-images.githubusercontent.com/25612037/128713100-c67b7d56-bf84-44b0-9131-3baeea11b63e.png)
However, I came to the conclusion that it should be ok to have additional logic representing LF semantics in the synthesis to refine the result of cycle detection. Do you agree?

While looking at this, I noticed that neither delayed nor physical connections actually break a cycle at the moment.
![delay_cycle_bug](https://user-images.githubusercontent.com/25612037/128714445-ece244be-4dae-4b0f-97b7-8d03f5071930.png)
Is that a bug in the cycle detection code or is my understating of the LF semantics wrong here?

**Comment by edwardalee** [comment]
Looks like the dependence graph is not correctly constructed.  I have not committed the change, but I tried fixing it so that the TopologyGraph is correctly constructed. But then the cycle detection algorithm is not working.  After correctly constructing the graph, I get this:

<img width="664" alt="image" src="https://user-images.githubusercontent.com/8513334/128865694-d62cf14f-9a8a-46ef-808f-6f8805982972.png">

Note that the delay edge is no longer highlighted, but it still thinks there is a cycle...

Marten?  If it were up to me, I would reimplement cycle detection by having ReactorInstance implement a DirectedGraph interface rather than creating a separate graph structure.

**Comment by a-sr** [comment]
The edge is not highlighted because of my hard-coded semantics that excludes delayed and physical connections (I may should have mentioned that my previous image was generated before I activated the special handling) but the fact that the other nodes are highlighted indicates that the analysis reports a cycle.

**Comment by lhstrh** [comment]
To me, it looks like `TopologyGraph` is doing the right thing. The cycle detection algorithm is working. The problem is that in `ReactorInstance`, the "mother of all graphs" from which the topology graph is constructed, dependencies are recorded irrespective of whether the connection is physical and or whether it has a delay. I'm pretty sure this didn't use to be the case. I can easily fix this by inserting something like:
```
    if (connection.isPhysical || connection.delay !== null) {
        return;
    }
```
in `ReactorInstance.establishPortConnections()`. But then no connections show up in the diagram at all. Also, a change like this will likely cause trouble for federated programs. After all, `PortInstance.dependsOnPort` is described as:
```
/** Port that sends messages to this port, if there is one. */
```
which is a much broader description than the "depends on" relationship that matters in the context of detecting causality loops.

There are now also extra data structures in `ReactorInstance` (e.g., `ReactorInstance.connections`, a `LinkedHashMap<Connection,LinkedHashMap<PortInstance,LinkedHashSet<PortInstance>>>`) just to support diagram synthesis, and these data structures get populated in the same methods that populate the maps that track "dependencies" between PortInstance objects. As for `TopologyGraph`, which is currently extremely straightforward (~100LOC), this leaves no option but to filter out the dependencies recorded in `ReactorInstance` that aren't actual dependencies. I suppose I could do this, but this would be an extremely inelegant (and inefficient) solution.

**Comment by lhstrh** [comment]
I should have a fix for this tomorrow...
