### ISSUE TITLE
CMake with C target

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/lingua-franca#476]
I'm having trouble with the cmake build with the C target. The `examples/C/Rhythm/SensorSimulator.lf` file no longer compiles.  In addition to the compile errors, it gives a warning: `Using the flags target property with cmake is dangerous.  Use cmake-include instead.`  I can't find adequate documentation on our wiki showing how to do that. In fact, [Writing Reactors in C](https://github.com/icyphy/lingua-franca/wiki/Writing-Reactors-in-C) includes an example, `Foo.lf`, which uses the flags target property together with cmake.  Where there is documentation, it doesn't work. I tried creating a file `SensorSimulator.txt` with the following:
```
find_package(lncurses REQUIRED) # Finds the lncurses library
target_link_libraries( ${LF_MAIN_TARGET} lncurses ) # Links the lncurses library
```
as instructed in the wiki and putting the target property `cmake-include: "SensorSimulator.txt"`.  This yields the following error:
```
CMake Error at /Users/eal/lingua-franca-master/git/lingua-franca/example/C/src/Rhythm/SensorSimulator.txt:1 (find_package):
  By not providing "Findlncurses.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "lncurses",
  but CMake did not find one.

  Could not find a package configuration file provided by "lncurses" with any
  of the following names:

    lncursesConfig.cmake
    lncurses-config.cmake

  Add the installation prefix of "lncurses" to CMAKE_PREFIX_PATH or set
  "lncurses_DIR" to a directory containing one of the above files.  If
  "lncurses" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:48 (include)
```
So how should I do this?  This really seems to add a great deal of unnecessary complexity.

For now, I will just set `cmake: false` in all the files I'm working with, but maybe we should revert the default to not use cmake by default?

**Comment by Soroosh129** [comment]
In terms of the contents of `SensorSimulator.txt`, the following is the correct entry:
```
find_package(Curses REQUIRED) # Finds the lncurses library
include_directories(${CURSES_INCLUDE_DIR}) # "The include directories needed to use Curses"
target_link_libraries( ${LF_MAIN_TARGET} ${CURSES_LIBRARIES} ) # Links the Curses library
```

I found this after searching for `cmake ncurses` and finding [this](https://cmake.org/cmake/help/latest/module/FindCurses.html) page.
The `FindCurses` module is already included in CMake, which indicates that we could find the package by dropping the `Find` and adding `find_package(Curses)`.  This is generally the CMake convention.

I agree that there might be a learning curve for using CMake for end users that have only worked with `gcc/g++`, me included. I will try to expand the documentation to alleviate that as best as I can.

In terms of the warning, this came up during one of our meetings. 
This is just a reminder that having the flags target property without identifying a compiler is dangerous, since flags are always compiler-specific. In the example in `Foo.lf`, a compiler is specified, so I think there shouldn't be a warning. I will look into that.

**Comment by Soroosh129** [comment]
I took a stab at clarifying the cmake capabilities, as well as the restrictions with the `flags` target property [here](https://github.com/icyphy/lingua-franca/wiki/Writing-Reactors-in-C#the-c-target-specification).

**Comment by edwardalee** [comment]
Thanks, this helps a lot, particularly the external links.  The page said this:

To do so, in the `src-gen` directory, run:
```
mkdir build && cd build
cmake ../
make
```

I changed this to:

To do so, in the `src-gen/ProgramName` directory, run:
```
mkdir build && cd build
cmake ../
make
```

Is this right?

**Comment by Soroosh129** [comment]
Yes that is correct. Thank you for clarifying that sentence.

**Comment by lhstrh** [comment]
Could we close this?
