### ISSUE TITLE
The import org.jetbrains cannot be resolved

### ISSUE THREAD

**Issue by Soroosh129** [lf-lang/lingua-franca#572]
After merging in #566, I get the following error in `org.lflang.TimeValue.java`:

<img width="356" alt="image" src="https://user-images.githubusercontent.com/4221770/136091523-ce4b4987-ab16-494d-ad70-0c515ff7c2ef.png">

```
The import org.jetbrains cannot be resolved
```

Is a dependency missing?

**Comment by lhstrh** [comment]
I suppose it works for Gradle and Maven, but not for Eclipse. Or maybe this requires a new Oomph install? IDK...

**Comment by Soroosh129** [comment]
I tried running the setup tasks again but the error persists. Isn't `org.jetbrains.annotations` an entirely new dependency? Is it used anywhere else? I don't see it in any of the `pom.xml` files.

**Comment by lhstrh** [comment]
The `pom.xml` has the Maven dependencies in it; Eclipse doesn't use Maven to build. Maybe we're better off removing these annotations for now? Or maybe @oowekyala or @a-sr can help?

**Comment by Soroosh129** [comment]
I opened #573 with a fix for now since Eclipse was unusable.

**Comment by cmnrd** [comment]
Since the Maven build is based on the Eclipse configuration, I would expect that it would also fail. However, it's hard to notice these dependency issues if you only work with `lfc` and the gradle build. It is probably a mistake that we don't actually build lfc and Epoch in our CI workflow. Also I am wondering: is there a way to trigger the Eclipse build in CI so that we can test our developer setup?

**Comment by a-sr** [comment]
`org.jetbrains.*` looks like a package from the Kotlin library and hence will always cause an error in the developer Eclipse since we removed the broken Kotlin support. I guess same, as dependencies to Kotlin classes, jetbrains packages should not be used in classes that are developed within Eclipse.
The build will probably work because we support Kotlin and its libraries in the gradle and maven build (see this [comment](https://github.com/lf-lang/lingua-franca/pull/562#discussion_r722986477)) but we decided to keep the code base that is currently developed in Eclipse free of Kotlin dependencies (see PR #437).
Since there is no proper provider for Kotlin/Jetbrains libraries in the Eclipse ecosystem, we cannot use these classes, unless we are willing to provides them ourself.

**Comment by oowekyala** [comment]
> Since there is no proper provider for Kotlin/Jetbrains libraries in the Eclipse ecosystem, we cannot use these classes, unless we are willing to provides them ourself.

Do you have an estimation of how much work providing those classes ourselves would represent? Jetbrains already builds an OSGi bundle. Would we need to put that on an eclipse update site or something?
