### ISSUE TITLE
Update description of C logging levels in the wiki

### ISSUE THREAD

**Issue by cmnrd** [lf-lang/lingua-franca#704]
I am not sure if this is the expected behavior or not, but if I set `logging: "warn"`, then `info_print` still prints messages. This is unintuitive to me, but according to our wiki this seems to be correct. The wiki states that "Use this for messages that should always be printed" and  I am pretty confused by this statement. Shouldn't info messages be excluded if I set the logging severity to "warning"?

**Comment by lhstrh** [comment]
I find this odd, too. Perhaps we should distinguish logging from printing and only have the former be affected by log levels.

**Comment by Soroosh129** [comment]
Yes, this looks like a bug. I double-checked and the log levels are as follows:
```
LOG_LEVEL_ERROR 0
LOG_LEVEL_WARNING 1
LOG_LEVEL_INFO 2
LOG_LEVEL_LOG 3
LOG_LEVEL_DEBUG 4
```

**Comment by lhstrh** [comment]
According to this list, and if the levels are properly enforced, only `error_print` messages will always be printed. I think main problem here is that we have what seems a generic (thread-safe) print function that is subject to log levels. Perhaps we should instead have `error_log`, `warning_log`, `info_log`, (omit `log_log` because what's that, anyway?), `debug_log`, and then just `print` to replace `info_print`.

**Comment by Soroosh129** [comment]
That's an interesting idea. 

At the moment, the default log level in the generated C code is 2. If info_prints are a nuisance for the user, they can be turned off by setting a lower log level. Maybe the current simplified design is easier to understand. Not sure.

**Comment by edwardalee** [comment]
I am unable to replicate @cmnrd's original problem. Are you in master?  When I set logging to `warn`, `info_print` messages are not printed.  I personally think this is quite useful behavior because it gives an easy way to have messages in benchmarks. The overhead of `info_print` when the logging level is `warn` or `error` should be quiet low.

Also, notice that the quotation marks are not needed, and the logging level is not case sensitive. You can set logging to `warn`, `WARN`, or `"warn"` and the effect is the same.

**Comment by cmnrd** [comment]
Hmm, I can't reproduce this either. I had this issue yesterday when I was working on the PiPrecise benchmark. Maybe I was doing something else wrong, or I should have done a clean.

However, I think the wiki description is misleading and it should be updated.

**Comment by oowekyala** [comment]
> omit log_log because what's that, anyway?

Just a suggestion, the standard Rust logging levels are called `error`, `warn`, `info`, `debug`, and `trace`. Maybe it would make sense to rename the C ones to match, removing that weird `log` level.

**Comment by edwardalee** [comment]
I'm not sure which wiki page you were looking at, but I updated this one: [Target Specification](https://github.com/lf-lang/lingua-franca/wiki/Target-Specification).  That page is missing anything about the `CCpp` target. Should we add that?

**Comment by cmnrd** [comment]
I was referring to [this section ](https://github.com/lf-lang/lingua-franca/wiki/Writing-Reactors-in-C#log-and-debug-information)in the C Documentation. For `print_info` it says "Use this for messages that should always be printed", which apparently isn't true. Also the error and warning print functions don't refer to the according log level.

**Comment by cmnrd** [comment]
Looks like the wiki page was updated
