### ISSUE TITLE
Rust main parameters need to be literals for CLI to compile

### ISSUE THREAD

**Issue by oowekyala** [lf-lang/lingua-franca#763]
If you build a reactor with CLI generation enabled, the main parameter default values need to be literals. This is because the default values are used by the CLI generator and are actually directly copy-pasted as a string as the default value for the help text. This string is then parsed by the CLI parser at runtime, and of course not interpreted as a Rust expression. We use this CLI generation framework that translates attributes to calls to the programmatic API to build the CLI parser. I don't see a way to fix this without switching to using the programmatic API of clap directly.

I found this out because I couldn't write `1u64 << 60`.
```rust
target Rust {
  cargo-features: [ "cli" ],
};
main reactor (param: u32(1u64 << 60)) { }
```

**Comment by cmnrd** [comment]
Who is doing the "copy-pasting to a string"? Is that something the CLI parser does, or is it rather our code generator? I don't know how this specific cli parser works, but from a general understanding I would assume that we provide the default values as a string from our code generator. If that is the case, then the mistake is to verbatim copy the code snippet to a string. Instead, we should treat it as an expression that we let the rust compiler handle and should convert the result to string. Given that there is some generic function `to_string(...)`, this should be simple.

With #561, we can now parse arbitrary types in C++. In order to parse a type `Foo`, all we need to do is to define the `<<` and `>>` stream operators for `Foo`, which implement the conversion from and to string. I think that is pretty cool and it would be great if we could do something similar in Rust.

**Comment by oowekyala** [comment]
> Who is doing the "copy-pasting to a string"? Is that something the CLI parser does, or is it rather our code generator?

The code generator

> If that is the case, then the mistake is to verbatim copy the code snippet to a string. Instead, we should treat it as an expression that we let the rust compiler handle and should convert the result to string. Given that there is some generic function to_string(...), this should be simple.

It's not that easy. The framework we use uses attributes as sugar over calls to the actual CLI parsing library.
So each parameter is generated into a struct field that looks something like
```
#[clap(long_name="--main-param", default="1u64 << 60", ...)]
main_param: u64
```
You can't put arbitrary expressions in attributes, only literals. In order to use the cli parsing library directly, we have to basically stop using that attribute processor, and completely change code generation of the cli module.

**Comment by cmnrd** [comment]
This seems to be fixed by a clap update. But we should probably add a test so that we no it stays working :)
