### ISSUE TITLE
Ensure that there is only a single hard-coded version number in the Java sources

### ISSUE THREAD

**Issue by lhstrh** [lf-lang/lingua-franca#980]
...and move its definition into the main `org.lflang` package.

**Comment by cmnrd** [comment]
Are you aware of any location other than `org.lflang.lfc.Main`? I couldn't find any. If we don't use the version, we probably do not need to move it. I also couldn't find a class where this would fit nicely.

Since we have the version number configured in our build tools, I wonder, is there a way to pass this on to the java code?

**Comment by lhstrh** [comment]
The `Help`->`About Epoch IDE` panel shows a version number, which is the reason I created this issue. I had assumed that the text was defined in a Java class, but it's defined in this XML file: `org.lflang.product/plugin.xml`...

**Comment by lhstrh** [comment]
Closing this because the automated workflow will now automatically adjust the version numbers in all locations, including the ones mentioned in this issue.
