### ISSUE TITLE
startup reactions in modal models

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/lingua-franca#999]
Currently, a startup reaction in a modal model reacts once when the program starts, but only if the startup reaction is defined in the initial mode. If the startup reaction is in some other mode, it is ignored and never invoked.

Wouldn't a better behavior be to invoke a startup reaction whenever a mode is entered, which for an initial mode is at the start of execution, but again each time the mode is entered via a reset transition?  A history transition would not invoke a startup reaction unless the mode is being entered for the first time.

**Comment by edwardalee** [comment]
Soroush had an interesting idea.  Currently, modal models will restart timers upon entering a mode with a reset transition. For any mode that is not an initial mode, we could do an AST transformation to create a timer with no period and a zero offset and modify each startup trigger to each reaction to be triggered instead by that timer. This way, the realization would be target-language independent. In particular, it would immediately work for Python.

**Comment by Soroosh129** [comment]
There is an issue that I hadn't considered.

Reactors with no modes in them can be instantiated within another mode.
This means that potentially all startup triggers should be substituted with timers that have a 0 offset and period.

Here is a self-contained program to demonstrate this:
```C
target C;
reactor Foo {
    state s:int(0)
    reaction(startup) {=
        info_print("%d", self->s);
    =}
}
reactor Bar {
    initial mode One {
        timer t(0, 1sec);
        reaction(t) -> reset(Two) {=
            info_print("Mode One");
            SET_MODE(Two);
        =}
    }
    mode Two {
        f = new Foo();
        reaction(startup) -> continue(One) {=
            info_print("Mode Two");
            SET_MODE(One);
        =}
    }
}
main reactor {
    b = new Bar();
}
```
In this example, the startup reaction in `Foo` should be triggered upon each reset transition.

It seems to be just easier to keep track of startup reactions for each mode and trigger them as soon as tag advances for modes that are active.

**Comment by a-sr** [comment]
As @Soroosh129 mentioned, the triggering of startup reactions upon reset also includes reactions on any level of inner reactor instantiation. In his example this makes sense and I found other examples such as [this test](https://github.com/lf-lang/lingua-franca/blob/master/test/C/src/TestForPreviousOutput.lf#L4-L21) where it might be crucial that upon reset the startup is executed. For example to create a fresh initial token/event that triggers some processing chain.
However, a reactor like [MotionDetector](https://github.com/lf-lang/lingua-franca/blob/master/example/C/src/TrainDoor/TrainDoor.lf#L36-L59) uses startup to spawn a thread, which triggers physical actions. Here, it would have very negative consequences if executed multiple times. This reactor is simply not written in a way that is compatible with the mode semantics of startup but we have no way to detect this.

The current handling of startup in modes is in my opinion only acceptable if the reaction is declared directly in the mode and not present via a mode instantiation. This way the programmer is aware of the different handling in modes. The same would be the case if we had a specific `entry` action for modes.
Yet, the main issue is composability, I think. We may need a different behavior for startup and shutdown in modes but the author of a reactor (e.g. in a library) might not anticipate this.

As an immediate workaround, I would suggest to follow a conservative approach and prohibit any reactor instantiation in modes that includes startup reactions, same as for shutdown (#1048).
But I hope we can come up with a concept that lifts this restriction a bit.

**Comment by lhstrh** [comment]
There would be a straightforward way to distinguish between reactions that should be executed upon entering with a reset transition vs. upon startup (which, for a mode would be synonymous with the first activation of the mode); add a `reset` trigger. A reaction that is expected to be triggered upon both reset and startup would simply declare both triggers. In the case of the reaction that spawn a thread, the only trigger should be `startup`.

**Comment by a-sr** [comment]
I agree, but when would you execute startup (resp. shutdown) in modes? If you do that once at the normal reactor startup, you would also have to execute reactions that are in inactive modes (same as discussed for shutdown).
If these reactions have effects, that could become problematic as well, e.g. an output is set from within an inactive mode, which contradicts the fundamental assumption of mutual exclusion.
Personally, I think this might be the best direction to go but we have to impose some limitations (such as prohibiting effects) but I am not sure if we can sufficiently enforce them to rule out all problematic situations safely.

**Comment by lhstrh** [comment]
I would argue the semantics in a mode should be the same as in a non-modal context: `startup` should be present once and once only at the first logical time instant that the reactor/mode is active. I agree that inactive modes should never be able to produce outputs, but I'm unsure why my proposal seemed to suggest otherwise -- I did not mean to suggest that.

The `reset` trigger and startup trigger should never be present at the same logical time; `reset` can only be active in mode entries that follow an initial activation during which `startup` was present. Operationally, we'd just have to keep track of whether a mode has ever been entered or not.

**Comment by Soroosh129** [comment]
> startup should be present once and once only at the first logical time instant that the reactor/mode is active.

Does this mean that `startup` will no longer align with a `timer t(0,0)` in all cases?

**Comment by edwardalee** [comment]
The [MotionDetector](https://github.com/lf-lang/lingua-franca/blob/7a7e3a5f063494527bc4962472ba9aec8c7b6d66/example/C/src/TrainDoor/TrainDoor.lf#L36-L59) example @Soroosh129 pointed out is interesting, but I think it can be solved more elegantly without introducing a new action.

First, that example is flawed, I think, because there is no `shutdown` reaction that causes the thread to terminate.

Second, we had failed to find a clear way to handle `shutdown` reactions, but I think I have one now, motivated by this example. Whenever a mode is entered via a reset transition, the following things should happen:

1. shutdown reactions should be invoked (this is new).
2. state variables and timers should be reset to their initial conditions.
3. startup reactions should be invoked.

The question remains: At what tags should these occur?  It seems that shutdown reactions should be invoked one microstep after the mode transition, and then startup reactions should be invoked two microsteps after.

**Comment by lhstrh** [comment]
> > startup should be present once and once only at the first logical time instant that the reactor/mode is active.
> 
> 
> 
> Does this mean that `startup` will no longer align with a `timer t(0,0)` in all cases?

No, that's not what I meant. It means that timers' offset are relative to the time of mode activation.

**Comment by edwardalee** [comment]
Also, I have realized that prohibiting shutdown reactions may inevitably lead to memory leaks.  Consider this scenario:

1. A reactor dynamically allocates memory in a startup reaction.
2. The memory is freed in shutdown.

In order to be able to use the memory, a pointer to it must be stored as a state variable. But that state variable will be reset to its initial conditions upon a reset transition, leaving the programmer with no mechanism for freeing the memory.

If we introduce a `reset` event, its reactions will have to be invoked before state variables are reset to their initial conditions. That cannot be at the same tag as events that react to a timer with offset 0, because reactions to that timer should see all state variables in their initial conditions.  So a single `reset` event won't be sufficient. We will need a `pre-reset` (???) and a `reset`, and the state variables will have to be reset in between.

I think it would be cleaner to use `startup` and `shutdown` for this purpose.

**Comment by edwardalee** [comment]
On the question of disallowing `startup` and `shutdown` reactions in modes, Marten and I just realized that this has a huge cost. It means that we won't be able to use many (most) library reactors within a mode.

**Comment by lhstrh** [comment]
> > > startup should be present once and once only at the first logical time instant that the reactor/mode is active.
> > 
> > 
> > Does this mean that `startup` will no longer align with a `timer t(0,0)` in all cases?
> 
> No, that's not what I meant. It means that timers' offset are relative to the time of mode activation.

Correction: you're right; the triggering would become simultaneous with `reset` rather than `startup` upon reentry via a reset transition. This could cause problems with contained reactors that are unaware of modal models.

**Comment by Soroosh129** [comment]
> In order to be able to use the memory, a pointer to it must be stored as a state variable. But that state variable will be reset to its initial conditions upon a reset transition, leaving the programmer with no mechanism for freeing the memory.

This is a good point. The state variable doesn't have to be inside the mode though, but it's easy to mistakenly put it within the mode and lose the pointer on a reset transition.

From this discussion, I also agree that disallowing `startup` and `shutdown` reactions could cause more problems than it solves.

> 1- shutdown reactions should be invoked (this is new).
> 2- state variables and timers should be reset to their initial conditions.
> 3- startup reactions should be invoked.

Do mode changes have to happen in superdense time?
What if we enforce that mode activations from reset transitions can only occur at microstep 0.
This ensures that all timers will always have microstep 0, for example, and allows for a clearer semantics: one microstep later after the transition request shutdown reactions are invoked. At the next available tag with microstep 0, startup reactions are invoked.

**Comment by edwardalee** [comment]
> Do mode changes have to happen in superdense time? What if we enforce that mode activations from reset transitions can only occur at microstep 0. This ensures that all timers will always have microstep 0, for example, and allows for a clearer semantics: one microstep later after the transition request shutdown reactions are invoked. At the next available tag with microstep 0, startup reactions are invoked.

This is an interesting suggestion, but I have this question: What is the "next available tag with microstep 0"? In particular, what if the mode being entered has a `timer t(0, 10 msec)`?

**Comment by rvhanxleden** [comment]
Marten just made me aware of this discussion. Here are my 2c, better be taken with a grain of salt (what a strange image this conjures), as I'm not that entrenched yet in the current mechanics of startup/shutdown.

First of all, it appears that we are, in a somewhat circumstantial way, running into the fact that "history transitions are evil." The usual argument for this is that they increase the state space, because we also have to remember things for states that we are not in anymore. Which is also pretty much why, e.g., SyncCharts don't have them. If we did not have them, we could simply shutdown a state whenever we leave it, and symmetrically startup a state whenever we enter it. But having said that, I think history transitions are quite useful to have.

One may now think of all kinds of mechanism to somehow restore such a symmetry also in the presence of history transitions. I think such symmetry might be key for a reasonably clean solution. E.g., one could also think of a "shutdown transition", which shuts down a state whenever it is left, as opposed to a standard transition. But I think that would complicate matters and not really resolve the issue.

I understand that one important concern is that we want to allow instantiation of reactors, which may include startup and/or shutdown reactors, in modes.

I also understand that our working hypothesis so far is that _no_ reaction is executed when it is in a mode that is not active. However, the way I understand the discussion so far, we already assume some magic that executes, at some point, shutdown reactions even for reactors that are in modes that are not active anymore. So I would not feel to bad to allow the same for startup reactions.

Thus, I think I'm currently leaning to the following. We provide the programmer with three signals:

1) startup - present for a reactor upon program startup. Possibly enclosing modes are ignored. Typically used for resource allocation.
2) shutdown - present for a reactor upon program termination. Possibly enclosing modes are ignored. Typically used for resource deallocation.
3) reset - present for a reactor whenever the enclosing mode is entered initially, or with a reset transition. Typically used for resetting state.

My conjecture - to be tested - is that with these three signals, the user can implement all reasonable desired behaviors in the target language.

Btw, Marten suggested to meet about this Monday, 8am Berkeley time. I'll send out a mail on that ...

**Comment by edwardalee** [comment]
I think this proposal could work.  After invoking startup reactions in an inactive mode (non-initial mode), any events it produced will have to be suspended, as if the we are exiting the mode.  E.g., consider a startup reaction that schedules a logical action.

Also, reset reactions will need to be invoked for all reactors that are not in modes at startup, presumably after the startup reactions.

Edward

---------
Edward A. Lee
EECS, UC Berkeley
***@***.***
http://eecs.berkeley.edu/~eal
